import {StyleSheet} from "react-native";

export const aggiungiPiantaStyles = StyleSheet.create({
    title: {
        fontSize: 24,
        fontWeight: "bold",
        marginBottom: 12,
        color: "#2E4A2C",
        textAlign: "center",
    },
    container: {
        flex: 1,
        backgroundColor: "#D4EDB6",
        borderRadius: 16,
        padding: 16,
        justifyContent: "space-between",
    },
    scrollArea: {
        width: "100%",
        flex: 1,
    },
    form: {
        alignItems: "center",
        gap: 12,
        paddingVertical: 8,
    },
    photoBox: {
        width: 120,
        height: 120,
        backgroundColor: "#fff",
        borderRadius: 8,
        justifyContent: "center",
        alignItems: "center",
        overflow: "hidden",
        marginBottom: 16,
    },
    photo: {
        width: "100%",
        height: "100%",
        borderRadius: 8,
    },
    photoText: {
        color: "#888",
        fontWeight: "500",
    },
    input: {
        width: "100%",
        height: 44,
        backgroundColor: "#fff",
        borderRadius: 8,
        paddingHorizontal: 12,
        fontSize: 16,
        color: "#2E4A2C",
        borderWidth: 0,
    },
    picker: {
        height: 44,
        alignSelf: "stretch",
        backgroundColor: "#fff",
        borderRadius: 8,
        paddingHorizontal: 12,
        fontSize: 16,
        color: "#2E4A2C",
        borderWidth: 0,
    },
    pickerText: {
        fontSize: 16,
        fontWeight: "normal",
    },
    buttonContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 24,
    },
    cancelButton: {
        backgroundColor: "#C69C91",
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 10,
        flex: 1,
        marginRight: 8,
    },
    addButton: {
        backgroundColor: "#7DBB8D",
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 10,
        flex: 1,
        marginLeft: 8,
    },
    cancelText: {
        color: "#2E4A2C",
        textAlign: "center",
        fontWeight: "bold",
    },
    addText: {
        color: "#2E4A2C",
        textAlign: "center",
        fontWeight: "bold",
    },
});