import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 24,
    },
    scrollArea: {
        width: "100%",
        flex: 1,
    },
    scrollContent: {
        alignItems: "center",
        paddingBottom: 20,
    },
    plantImageContainer: {
        position: "relative",
        marginBottom: 24,
        width: 200,
        height: 200,
        borderRadius: 20,
        overflow: 'hidden',
    },
    plantImage: {
        width: '100%',
        height: '100%',
        resizeMode: "cover",
    },
    healthTag: {
        position: "absolute",
        bottom: 10,
        left: 10,
        backgroundColor: "#4CAF50",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
    },
    waterTag: {
        position: "absolute",
        top: 10,
        right: 10,
        backgroundColor: "#FFD43B",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
    },
    tagText: {
        fontWeight: "bold",
        fontSize: 12,
        textAlign: 'center',
    },
    healthTagText: {
        fontWeight: "bold",
        fontSize: 12,
        color: "white",
        textAlign: 'center',
    },
    infoBox: {
        backgroundColor: "#F8F8F8",
        borderRadius: 16,
        padding: 20,
        width: "100%",
        marginBottom: 24,
    },
    infoTitle: {
        fontWeight: "bold",
        fontSize: 18,
        marginBottom: 12,
        textAlign: 'center',
        color: "#2E4A2C",
    },
    infoText: {
        fontSize: 16,
        marginBottom: 8,
        textAlign: 'left',
        color: "#2E4A2C",
    },
    editableInput: {
        width: "100%",
        height: 44,
        backgroundColor: "#fff",
        borderRadius: 8,
        paddingHorizontal: 12,
        fontSize: 16,
        color: "#2E4A2C",
        borderWidth: 1,
        borderColor: "#DDD",
        marginBottom: 12,
    },
    rowContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: 12,
    },
    halfInput: {
        width: '48%',
    },
    buttonContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
        marginBottom: 7,
    },
    deleteButton: {
        backgroundColor: "#C69C91",
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 10,
        flex: 1,
        marginRight: 8,
    },
    cancelButton: {
        backgroundColor: "#C69C91",
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 10,
        flex: 1,
        marginRight: 8,
    },
    editButton: {
        backgroundColor: "#7DBB8D",
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 10,
        flex: 1,
        marginLeft: 8,
    },
    saveButton: {
        backgroundColor: "#4CAF50",
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 10,
        flex: 1,
        marginLeft: 8,
    },
    buttonText: {
        color: "#2E4A2C",
        textAlign: "center",
        fontWeight: "bold",
    },
    dateFieldContainer: {
        width: '100%',
        marginBottom: 12,
    },
    dateFieldLabel: {
        fontSize: 16,
        color: '#2E4A2C',
        marginBottom: 4,
    },
    dateInput: {
        backgroundColor: '#FFF',
        height: 44,
        borderRadius: 8,
        paddingHorizontal: 12,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#DDD',
    },
    dateInputText: {
        fontSize: 16,
        color: '#2E4A2C',
    },
    editOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(0,0,0,0.7)',
        padding: 10,
        alignItems: 'center',
    },
    editOverlayText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 14,
    },
});